# Lian Le Ma unified launcher
# Detect LAN IP -> write app/backend env -> start Flask pose service + FastAPI + Expo.

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $MyInvocation.MyCommand.Definition
$appDir = Join-Path $root "app"
$backendDir = Join-Path $root "backend"
$appEnvFile = Join-Path $appDir ".env"
$backendEnvFile = Join-Path $backendDir ".env"
$preferredModelPort = 4000
$preferredApiPort = 8000

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  Lian Le Ma - Unified Launcher" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

function Get-LanIP {
    $candidates = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object {
            $_.IPAddress -notlike "127.*" -and
            $_.IPAddress -notlike "169.254.*" -and
            $_.PrefixOrigin -ne "WellKnown"
        }

    foreach ($keyword in @("Wi-Fi", "WLAN")) {
        $hit = $candidates | Where-Object { $_.InterfaceAlias -match $keyword } | Select-Object -First 1
        if ($hit) { return $hit.IPAddress }
    }

    $ethernet = $candidates | Where-Object {
        $_.InterfaceAlias -notmatch "vEthernet|VMware|VirtualBox|Loopback|WSL|Hyper-V"
    } | Select-Object -First 1
    if ($ethernet) { return $ethernet.IPAddress }
    if ($candidates) { return ($candidates | Select-Object -First 1).IPAddress }
    return $null
}

function Test-PortAvailable([int]$Port) {
    $listener = Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue
    return -not $listener
}

function Select-Port([int]$PreferredPort) {
    if (Test-PortAvailable $PreferredPort) {
        return $PreferredPort
    }
    for ($port = $PreferredPort + 1; $port -lt $PreferredPort + 50; $port++) {
        if (Test-PortAvailable $port) {
            return $port
        }
    }
    throw "No free port found near $PreferredPort"
}

function Test-PythonCandidate([string]$PythonExe) {
    if (-not (Test-Path $PythonExe)) {
        return $false
    }
    $probe = & $PythonExe -c "import cv2, fastapi, uvicorn, torch; print('ok')" 2>$null
    return $LASTEXITCODE -eq 0
}

function Resolve-PythonExe {
    $candidates = @(
        "C:\Users\10084\anaconda3\python.exe",
        "C:\Users\10084\anaconda3\envs\pytorch\python.exe"
    )

    foreach ($candidate in $candidates) {
        if (Test-PythonCandidate $candidate) {
            return $candidate
        }
    }

    $probe = python -c "import cv2, fastapi, uvicorn, torch; print('ok')" 2>$null
    if ($LASTEXITCODE -eq 0) {
        return "python"
    }

    throw "No Python interpreter with cv2/fastapi/uvicorn/torch was found."
}

$pythonExe = Resolve-PythonExe
$modelPort = Select-Port $preferredModelPort
$apiPort = Select-Port $preferredApiPort

$ip = Get-LanIP
if (-not $ip) {
    Write-Host "[WARN] Could not auto-detect LAN IP." -ForegroundColor Yellow
    $ip = Read-Host "Enter this PC's LAN IP (for example 192.168.1.10)"
}

$modelBaseUrl = "http://${ip}:${modelPort}"
$apiBaseUrl = "http://${ip}:${apiPort}"
$voiceOutputDir = Join-Path $backendDir "runtime\\audio"
$voiceSampleDir = Join-Path $backendDir "runtime\\samples"

Write-Host "[1/5] Python: $pythonExe" -ForegroundColor Green
Write-Host "[2/5] LAN IP: $ip" -ForegroundColor Green
Write-Host "      Flask pose service: $modelBaseUrl"
Write-Host "      FastAPI business API: $apiBaseUrl"

$appEnvContent = @"
# Auto-generated by start.ps1. Re-run after switching networks.
EXPO_PUBLIC_API_BASE_URL=$apiBaseUrl
EXPO_PUBLIC_MODEL_BASE_URL=$modelBaseUrl
EXPO_PUBLIC_MODEL_MODE=manual
"@
Set-Content -Path $appEnvFile -Value $appEnvContent -Encoding ASCII
Write-Host "[3/5] Wrote $appEnvFile" -ForegroundColor Green

$backendEnvContent = @"
# Auto-generated by start.ps1. Contains only local runtime wiring.
MODEL_SERVICE_URL=http://127.0.0.1:$modelPort
BACKEND_HOST=0.0.0.0
BACKEND_PORT=$apiPort
PUBLIC_BASE_URL=$apiBaseUrl
VOICE_OUTPUT_DIR=$voiceOutputDir
VOICE_SAMPLE_DIR=$voiceSampleDir
"@
Set-Content -Path $backendEnvFile -Value $backendEnvContent -Encoding ASCII
Write-Host "[4/5] Wrote $backendEnvFile" -ForegroundColor Green

Write-Host "[5/5] Launching pose service, backend API, and Expo..." -ForegroundColor Green

Start-Process powershell -ArgumentList @(
    "-NoExit", "-Command",
    "`$env:PORT='$modelPort'; `$env:POSE_APP_PORT='$modelPort'; `$env:FLASK_DEBUG='0'; cd '$root'; Write-Host '== Flask pose service (port $modelPort) =='; & '$pythonExe' web_app.py"
)

Start-Sleep -Seconds 4

Start-Process powershell -ArgumentList @(
    "-NoExit", "-Command",
    "cd '$backendDir'; Write-Host '== FastAPI backend (port $apiPort) =='; & '$pythonExe' -m uvicorn app.main:app --host 0.0.0.0 --port $apiPort"
)

Start-Sleep -Seconds 4

Start-Process powershell -ArgumentList @(
    "-NoExit", "-Command",
    "cd '$appDir'; Write-Host '== Expo dev server =='; npx expo start"
)

Write-Host ""
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  Started. Next steps:" -ForegroundColor Cyan
Write-Host "  - Phone: connect to the same Wi-Fi and scan the Expo QR code" -ForegroundColor White
Write-Host "  - Browser: press 'w' in the Expo window or open http://localhost:8081" -ForegroundColor White
Write-Host "  - App API URL: $apiBaseUrl" -ForegroundColor White
Write-Host "  - Model service URL: $modelBaseUrl" -ForegroundColor White
Write-Host "  - Close the three new windows to stop all services" -ForegroundColor White
Write-Host "==================================================" -ForegroundColor Cyan
